config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  unauthenticated :user do
    root to: 'home#index', id: 'index', as: :unauthenticated_root
  end

  devise_scope :user do
    authenticate :user do
      resources :assessments
      resources :questions do 
        resources :answers, except: [:index, :show]
      end
      resources :dashboard, only: [:index]
    end
    root to: "dashboard#index", as: :authenticated_user
  end
  # Defines the root path route ("/")
  root 'home#index'
end

app/models/answer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  label       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :integer
#
class Answer < ApplicationRecord
  belongs_to :question
  validates :label, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assessment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assessments
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  state       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
class Assessment < ApplicationRecord
  belongs_to :user, optional: true
  has_many :assessment_questions
  has_many :questions, through: :assessment_questions

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
end

app/models/assessment_question.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assessment_questions
#
#  id            :integer          not null, primary key
#  question_id   :integer
#  assessment_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class AssessmentQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :assessment
end

app/models/question.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  label       :string
#  description :string
#  state       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  type        :string
#
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :assessment_questions
  has_many :assessments, through: :assessment_questions

  validates :label, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :question_type, presence: true

  # Question Types:
  QUESTION_TYPES = [
    MULTI = 'multiple-choice',
    DROPDOWN = 'dropdown',
    TEXT = 'text', # Think about this one??? v2?
    CHECKBOX = 'checkbox' # True || False
  ].freeze

  # States
  # PENDING = 'pending'
  # ACTIVED = 'actived'
  # ARCHIVED = 'archived'

  # state_machine :state, initial: PENDING do
  #   event 'activate' do
  #     transition(PENDING => ACTIVED)
  #   end

  #   event 'archived' do
  #     transition([PENDING, ACTIVED] => ARCHIVED)
  #   end
  # end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  firstname  :string
#  lastname   :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :assessments
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  def index
    questions = Question.all

    render json: questions
    render json: QuestionSerializer.new(questions)

    # if questions
    #   render json: {status: "SUCCESS", message: "Fetched all the questions successfully", data: questions}, status: :ok
    # else
    #   render json: questions.errors, status: :bad_request
    # end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/assessments_controller.rb
# frozen_string_literal: true

class AssessmentsController < ApplicationController
  before_action :load_assessments
  before_action :load_assessment, only: %i[edit update destroy]
  before_action :load_questions, only: %i[edit]

  def index; end

  def edit; end

  def new
    @assessment = Assessment.new
  end

  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to assessments_url, notice: 'assessment was successfully created' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @assessment.update!(assessment_params)
        format.html { redirect_to assessments_url, notice: 'assessment was successfully created' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @assessment.destroy!
        format.html { redirect_to assessments_url, notice: 'Assessment was successfully deleted' }
      else
        format.html { redirect_to assessments_url, status: :unprocessable_entity }
      end
    end
  end

  private

  def assessment_params
    params.require(:assessment).permit(:title, :description)
  end

  def load_assessments
    @assessments = Assessment.all
  end

  def load_assessment
    @assessment = Assessment.find_by(id: params[:id])
  end

  def load_questions
    # @questions = @assessment.questions
    @questions = Question.all
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :load_questions, only: [:index]
  before_action :load_question, only: %i[show edit update destroy]

  def index; end

  def new
    @question = Question.new
  end

  # rubocop:disable Layout/LineLength
  def create
    @question = Question.new(question_params)

    if @question.save
      respond_to do |format|
        # format.html { redirect_to edit_assessment_path(id: params[:assessment_id]), notice: "question was successfully created." }
        format.html { redirect_to questions_path, notice: 'question was successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
  # rubocop:enable Layout/LineLength

  def update
    if @question.update!(question_params)
      respond_to do |format|
        format.html { redirect_to questions_path, notice: 'question was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'question was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_path, notice: 'question was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'question was successfully destroyed.' }
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def load_questions
    @questions = Question.all
  end

  def question_params
    params.require(:question).permit(:label, :description, :question_type)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # def render_turbo_stream_flash_messages
  #   turbo_stream.prepend "flash", partial: "layouts/flash"
  # end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/assessments/_assessment.html.erb
<div class="grid grid-cols-3">
  <% assessments.each do |assessment| %>
    <div class="text-center max-w-sm rounded overflow-hidden shadow-lg p-5 m-4">
      <h1 class="text-3xl font-black"><%= assessment.title %></h1>
      <p class="font-light mt-1 mb-2"><%= assessment.description %></p>
      <%= link_to "Edit", edit_assessment_path(assessment), class: "btn-main pb-2" %>
      <%= link_to 'Delete', assessment_path(assessment), class: "btn-danger pb-2",
        data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    </div>
  <% end %>
</div>

app/views/assessments/_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= form_with(model: @assessment) do |form| %>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-12 sm:col-span-12">
                <%= form.label :title, class: "form-label" %>
                <%= form.text_field :title, placeholder: "title...", class: "form-field" %>
              </div>

              <div class="col-span-12 sm:col-span-12">
                <%= form.label :description, class: "form-label" %>
                <%= form.text_area :description, placeholder: "title...", class: "form-field" %>
              </div>

              <%# <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                <label for="postal-code" class="form-label">ZIP / Postal code</label>
                <input type="text" name="postal-code" id="postal-code" autocomplete="postal-code" class="form-field">
              </div> %>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%= form.submit "Save", class: "inline-flex justify-center btn-main" %>
            <%= link_to "Back", assessments_path, class: "btn-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/assessments/_question_row.html.erb
<% @questions.each do |question| %>
  <tr class="bg-white border-b">
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= check_box_tag 'select_all',
        'all',
        false,
        class: 'h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 mr-4"',
        # TODO: implement stimulus controller...
        data: {
          # target:"shared-table.selectAllCheckbox",
          # action:"click->shared-table#toggleSelectAll"
        }
      %>
    </td>
    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
      <%= question.label %>
    </td>
    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
      <%= question.description %>
    </td>
    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
      <%= question.question_type %>
    </td>
  </tr>
<% end %>

app/views/assessments/_question_table.html.erb
<div class="flex flex-col">
  <div class="bg-white overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden shadow">
        <table class="min-w-full text-center">
          <thead class="border-b bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-4"></th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Label
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Description
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Question Type
              </th>
            </tr>
          </thead class="border-b">
          <tbody>
            <%= render partial: "question_row", locals: { questions: @questions } %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/assessments/edit.html.erb
<div class="mt-4">
  <h1 class="mb-4 text-4xl font-black">Edit Assessment</h1>
</div>
<%= render partial: "form", locals: { assessment: @assessment } %>

<div class="mt-4">
  <h3 class="text-3xl font-bold mb-8">Add Questions</h3>
</div>

<%= render partial: "question_table", locals: { questions: @questions } %>

app/views/assessments/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<div class="mt-4">
  <h1 class="mb-4 text-4xl font-black">Assessments</h1>
</div>
<%= render partial: "assessment", locals: { assessments: @assessments } %>
<div class="mt-4">
  <%= link_to "New", new_assessment_path, class: "btn-main" %>
</div>

app/views/assessments/new.html.erb
<div class="mt-4">
  <h1 class="mb-4 text-4xl font-black">New Assessment</h1>
</div>
<%= render partial: "form", locals: { assessment: @assessment } %>

app/views/dashboard/index.html.erb
<div class="mt-4">
  <h1 class="mb-4 text-4xl font-black">Your Dashboard</h1>
</div>

<div class="flex justify-center">
  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-sm m-5">
    <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">Assessments</h5>
    <p class="text-gray-700 text-base mb-4">
      See all assessments
    </p>
    <%= link_to "Go", assessments_path, class: "btn-main" %>
  </div>
  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-sm m-5">
    <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">Questions</h5>
    <p class="text-gray-700 text-base mb-4">
      See all questions
    </p>
    <%= link_to "Go", questions_path, class: "btn-main" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="isolate bg-white">
  <div class="px-6 pt-6 lg:px-8">
    <div>
      <nav class="flex h-9 items-center justify-between" aria-label="Global">
        <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
          <a href="#" class="font-semibold text-gray-900 hover:text-gray-900">About</a>
          <%= link_to "Assessments", assessments_path, class: "font-semibold text-gray-900 hover:text-gray-900" %>
      </nav>
    </div>
  </div>
  <main>
    <div class="relative px-6 lg:px-8">
      <div class="mx-auto max-w-3xl pt-20 pb-32 sm:pt-48 sm:pb-40">
        <div>
          <div>
            <h1 class="text-4xl font-bold tracking-tight sm:text-center sm:text-6xl">Welcome to Quiz Me</h1>
            <p class="mt-6 text-lg leading-8 text-gray-600 sm:text-center">Choose from carefully thought interview questions or make your own</p>
            <div class="mt-8 flex gap-x-4 sm:justify-center">
              <%= link_to "Log in", new_user_session_path, class: "btn-main" %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/layouts/_navbar.html.erb
<nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-gray-900 text-gray-200 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
    <div class="container-fluid">
          <%= link_to "RubyView",
                root_path,
                class: "text-xl text-white font-semibold" %>
    </div>
    <div class="container-fluid">
      <% if user_signed_in? %>
          <%= button_to "Sign out",
                    destroy_user_session_path,
                    method: :delete,
                    class: "btn-main" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p> 
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= form_with(model: @question) do |form| %>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-12 sm:col-span-12">
                <%= form.label :label, class: "form-label" %>
                <%= form.text_field :label, placeholder: "title...", default_value: @question.label, class: "form-field" %>
              </div>

              <div class="col-span-12 sm:col-span-12">
                <%= form.label :description, class: "form-label" %>
                <%= form.text_area :description, placeholder: "description...", default_value: @question.description, class: "form-field" %>
              </div>

              <div class="col-span-12 sm:col-span-12">
                <%= form.label :question_type, class: "form-label" %>
                <%= form.select(:question_type, Question::QUESTION_TYPES, { include_blank: false }, { class: "form-field" }) %>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%= link_to "Cancel", questions_path, class: "btn-secondary" %>
            <%= form.submit "Save", class: "inline-flex justify-center btn-main" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/_question.html.erb
<%= turbo_frame_tag question do %>
  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-sm m-5">
    <%= link_to question.label,
                question_path(question),
                data: { turbo_frame: "_top" } %>
    <div class="flex">
      <%= link_to "Edit",
                  edit_question_path(question),
                  class: "btn-main mr-4" %>
      <%= button_to "Delete",
                    question_path(question),
                    method: :delete,
                    class: "btn-danger" %>
    </div>
  </div>
<% end %>

app/views/questions/create.turbo_stream.erb
  <%= turbo_stream.prepend "questions", @question %>
  <%= turbo_stream.update Question.new, "" %>

<%# <%= render_turbo_stream_flash_messages %> 

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>
<%# <%= render_turbo_stream_flash_messages %> 

app/views/questions/edit.html.erb
<main class="container">

  <div class="header">
    <h1>Edit question</h1>
  </div>

  <%= turbo_frame_tag @question do %>
    <%= render "form", question: @question %>
  <% end %>
</main>

app/views/questions/index.html.erb
<div class="mt-4">
  <h1 class="mb-4 text-4xl font-black">Add Questions</h1>
</div>

  <div class="m-4">
    <%= link_to "New question",
                new_question_path,
                class: "btn-main",
                data: { turbo_frame: dom_id(Question.new) } %>
  </div>

  <%= turbo_frame_tag Question.new %>

  <%= turbo_frame_tag "questions" do %>
    <div class="grid grid-cols-3">
      <%= render @questions %>
    </div>
  <% end %>

app/views/questions/new.html.erb
    <%= link_to sanitize("&larr; Back to quotes"), assessments_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag @question do %>
    <%= render "form", question: @question %>
  <% end %>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.replace @question %>
<%# <%= render_turbo_stream_flash_messages %> 